### ISSUE TITLE
Feature Request: Improve customizability with a user-editable CSS stylesheet

### ISSUE THREAD

**Issue by menturi** [ansh/jiffyreader.com#126]
### Current behavior ###
The fixation portions of the words are bolded.

### Suggested behavior ###

The fixation portions of the words are customizable to remove bolding, add underline, or apply any user-specified CSS stylesheet.

### Rational ###

Although many individuals find it useful, others find the style to be difficult to read. Using bold for the fixation portions might place too much emphasis on that part of the text. Some things I have read:
- Straining on the eyes or sensory overload [1,2]
- Bolded text is traditionally used for emphasis, changing the way one reads the text. I've read some read it with more stress, yelling, slower, or sarcasm voice (particularly if reading with an internal monologue) [1,2]
- It leads to reading with stutter [1,2]
- Some join the bolded parts together and read unintelligible text. [1]

[[1]](https://www.reddit.com/r/coolguides/comments/ut3x75/bionic_reading_does_this_help_you/), [[2]](https://www.reddit.com/r/interestingasfuck/comments/usgac8/bionic_reading_using_font_weights_to_increase/)

Using a more subtle style change rather than bolding could improve readability for some. Of course, it will be difficult to make everybody happy. Allowing for user-specified custom CSS stylesheet will allow for those who like to tinker to get it to look *just right* for their needs while relieving some of the burden from the developer for implementing all possible and reasonable customization options.

### Opinion ###

I personally find the large amount of bolded text jarring. Playing around, I have found removing the bold and replacing it with a dotted underline to work better for me. This is already possible, in part, using Jiffy Reader in conjunction with the Stylus extension. Unfortunately, I am unable to override the extension's CSS so easily due to the use of !important CSS keyword by the extension. Having the user be able to modify the CSS used by extension would fix this issue while also allowing others to customize to their heart's content.

## Tracked through
- [ ] #127

**Comment by asieduernest12** [comment]
@menturi I see your point and totally user centric to allow them make modifications. The !important
Modifier was removed from the bold style in the latest 0.0.7-alpha-opacity release

**Comment by asieduernest12** [comment]
## Todos 
- [] popup.html: add extra options in saccades color. The extra options will be saccades-solid-line, saccades-dash-line, saccades-dotted-line, saccades-strickthrough-line 
- [] give the options the same value as the text it shows 
- [] change saccades color label to saccades style 
- [] bookmarklet/index.js add the new lines options to the saccades color state array.
- [] rename any refs to saccades color as saccades style
- [] rename the saccades action transition method maps
- [] bookmarklet/esbuild.js : rename saccades color to saccades styles and update reference to the transition function accordingly
- [] contentstyle.scss:

**Comment by asieduernest12** [comment]
> ### Current behavior
> The fixation portions of the words are bolded.
> 
> ### Suggested behavior
> The fixation portions of the words are customizable to remove bolding, add underline, or apply any user-specified CSS stylesheet.
> 
> ### Rational
> Although many individuals find it useful, others find the style to be difficult to read. Using bold for the fixation portions might place too much emphasis on that part of the text. Some things I have read:
> 
> * Straining on the eyes or sensory overload [1,2]
> * Bolded text is traditionally used for emphasis, changing the way one reads the text. I've read some read it with more stress, yelling, slower, or sarcasm voice (particularly if reading with an internal monologue) [1,2]
> * It leads to reading with stutter [1,2]
> * Some join the bolded parts together and read unintelligible text. [1]
> 
> [[1]](https://www.reddit.com/r/coolguides/comments/ut3x75/bionic_reading_does_this_help_you/), [[2]](https://www.reddit.com/r/interestingasfuck/comments/usgac8/bionic_reading_using_font_weights_to_increase/)
> 
> Using a more subtle style change rather than bolding could improve readability for some. Of course, it will be difficult to make everybody happy. Allowing for user-specified custom CSS stylesheet will allow for those who like to tinker to get it to look _just right_ for their needs while relieving some of the burden from the developer for implementing all possible and reasonable customization options.
> 
> ### Opinion
> I personally find the large amount of bolded text jarring. Playing around, I have found removing the bold and replacing it with a dotted underline to work better for me. This is already possible, in part, using Jiffy Reader in conjunction with the Stylus extension. Unfortunately, I am unable to override the extension's CSS so easily due to the use of !important CSS keyword by the extension. Having the user be able to modify the CSS used by extension would fix this issue while also allowing others to customize to their heart's content.

**Comment by asieduernest12** [comment]
> ### Current behavior
> The fixation portions of the words are bolded.
> 
> ### Suggested behavior
> The fixation portions of the words are customizable to remove bolding, add underline, or apply any user-specified CSS stylesheet.
> 
> ### Rational
> Although many individuals find it useful, others find the style to be difficult to read. Using bold for the fixation portions might place too much emphasis on that part of the text. Some things I have read:
> 
> * Straining on the eyes or sensory overload [1,2]
> * Bolded text is traditionally used for emphasis, changing the way one reads the text. I've read some read it with more stress, yelling, slower, or sarcasm voice (particularly if reading with an internal monologue) [1,2]
> * It leads to reading with stutter [1,2]
> * Some join the bolded parts together and read unintelligible text. [1]
> 
> [[1]](https://www.reddit.com/r/coolguides/comments/ut3x75/bionic_reading_does_this_help_you/), [[2]](https://www.reddit.com/r/interestingasfuck/comments/usgac8/bionic_reading_using_font_weights_to_increase/)
> 
> Using a more subtle style change rather than bolding could improve readability for some. Of course, it will be difficult to make everybody happy. Allowing for user-specified custom CSS stylesheet will allow for those who like to tinker to get it to look _just right_ for their needs while relieving some of the burden from the developer for implementing all possible and reasonable customization options.
> 
> ### Opinion
> I personally find the large amount of bolded text jarring. Playing around, I have found removing the bold and replacing it with a dotted underline to work better for me. This is already possible, in part, using Jiffy Reader in conjunction with the Stylus extension. Unfortunately, I am unable to override the extension's CSS so easily due to the use of !important CSS keyword by the extension. Having the user be able to modify the CSS used by extension would fix this issue while also allowing others to customize to their heart's content.

## Todos 
- [ ] popup.html: add extra options in saccades color. The extra options will be saccades-solid-line, saccades-dash-line, saccades-dotted-line, saccades-strickthrough-line 
- [ ] give the options the same value as the text it shows 
- [ ] change saccades color label to saccades style 
- [ ] bookmarklet/index.js add the new lines options to the saccades color state array.
- [ ] rename any refs to saccades color as saccades style
- [ ] rename the saccades action transition method maps
- [ ] bookmarklet/esbuild.js : rename saccades color to saccades styles and update reference to the transition function accordingly
- [ ] contentstyle.scss:

**Comment by asieduernest12** [comment]
## Todo
- [ ] implement more saccades styling options

**Comment by asieduernest12** [comment]
## Todo 
- [ ] implement more saccades styling options and add to existing saccades color feature
