### ISSUE TITLE
Feat: implement more saccades styling options and add to existing saccades color feature

### ISSUE THREAD

**Issue by asieduernest12** [ansh/jiffyreader.com#127]
Feat: implement more saccades styling options and add to existing saccades color feature

_Originally posted by @asieduernest12 in https://github.com/ansh/jiffyreader.com/issues/126#issuecomment-1159771638_

## Todos 
- [ ] popup.html: add extra options in saccades color. The extra options will be saccades-solid-line, saccades-dash-line, saccades-dotted-line, saccades-strickthrough-line 
- [ ] give the options the same value as the text it shows 
- [ ] change saccades color label to saccades style 
- [ ] bookmarklet/index.js add the new lines options to the saccades color state array.
- [ ] rename any refs to saccades color as saccades style
- [ ] rename the saccades action transition method maps
- [ ] bookmarklet/esbuild.js : rename saccades color to saccades styles and update reference to the transition function accordingly
- [ ] contentstyle.scss:
