### ISSUE TITLE
popup.html: add extra saccades styling options under saccades color

### ISSUE THREAD

**Issue by asieduernest12** [ansh/jiffyreader.com#129]
## Todo
 

- [x] add extra options in saccades color. The extra options will be saccades-solid-line, saccades-dash-line, saccades-dotted-line, saccades-strickthrough-line
- [x]  give the options the same value as the text it shows
- [x]  change saccades color label to saccades style

**Comment by asieduernest12** [comment]
## Todo
 

- [ ] add extra options in saccades color. The extra options will be saccades-solid-line, saccades-dash-line, saccades-dotted-line, saccades-strickthrough-line
- [ ]  give the options the same value as the text it shows
- [ ]  change saccades color label to saccades style

**Comment by asieduernest12** [comment]
thank you @rezwan-hossain
