### ISSUE TITLE
bookmarklet: add new saccade styling states to existing saccades-color state with further changes

### ISSUE THREAD

**Issue by asieduernest12** [ansh/jiffyreader.com#130]
## Todo inside Bookmarklet dir 
- [ ] index.js: add the new lines options to the saccades color state array.
- [ ] rename any refs to saccades color as saccades style
- [ ] rename the saccades action transition method maps
- [ ] bookmarklet/esbuild.js : rename saccades color to saccades styles and update reference to the transition function accordingly
